### ISSUE TITLE
Unable to import gwpy in notebooks of google colab

### ISSUE THREAD

**Issue by TheVictorMunoz** [gw-odw/odw-2019#12]
Hi, I'm trying to run the notebook:

Tuto 1.2 Open Data access with GWpy.ipynb

On the google colab platform. However, when importing the gwpy module I get the error:

------------------------------------------------------------------------------------
/usr/local/lib/python3.6/dist-packages/gwpy/plot/rc.py in <module>()
     77     'text.usetex': True,
     78     'text.latex.preamble': (
---> 79         rcParams.get('text.latex.preamble', []) + tex.MACROS),
     80     # use bigger font for labels (since the font is good)
     81     'font.family': ['serif'],

TypeError: must be str, not list
--------------------------------------------------------------------------------

how can I overcome this?

Cheers,
Víctor

**Comment by jkanner** [comment]
Hi Victor,

Thank you for flagging this.

This is a bug in the tutorial software stack, due to evolving software libraries.  We’ll take a look, and see if we can fix it over the next few weeks.

For now, I think the tutorial will run if you follow these steps to use the latest versions of the gwpy and gwosc libraries.  At least, this worked for me!  I recommend starting with a fresh google co-lab session.

1) In the runtime menu, click “change runtime type”, and ensure you are running in a python 3 environment.

2) Remove the “pip install” lines  (the top two lines of the notebook) and replace with this:
! pip install gwpy gwosc

3) From the runtime menu, click “run all”

Note, a similar trick should work with the other notebooks, though you may have to add additional packages (e.g. pycbc) in some cases.  Good luck!

Best,
 jonah


On Jan 26, 2020, at 12:41 PM, victor muñoz albornoz <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi, I'm trying to run the notebook:

Tuto 1.2 Open Data access with GWpy.ipynb

On the google colab platform. However, when importing the gwpy module I get the error:

________________________________

/usr/local/lib/python3.6/dist-packages/gwpy/plot/rc.py in ()
77 'text.usetex': True,
78 'text.latex.preamble': (
---> 79 rcParams.get('text.latex.preamble', []) + tex.MACROS),
80 # use bigger font for labels (since the font is good)
81 'font.family': ['serif'],

TypeError: must be str, not list

how can I overcome this?

Cheers,
Víctor

**Comment by TheVictorMunoz** [comment]
Great, this worked.

Thanks!
